// Code generated by "const generator". DO NOT EDIT.
package config

import (
	"rtc/pkg/rtc"
)

const (
	/* This is my awesome feature description1 */
	SomeExampleFeatureKey1 = rtc.Key("some_example_feature_key1")
)
