// Code generated by "const generator". DO NOT EDIT.
package config

import (
	"rtc/pkg/rtc"
)

const (
	/* This is my awesome feature description2 */
	SomeExampleFeatureKey2 = rtc.Key("some_example_feature_key2")
)
